services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        volumes:
            - .:/var/www/frontend
        ports:
            - "8080:8080"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
