services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        volumes:
            - .:/var/www/backend
        networks:
            - app-network

    db:
        image: postgres:15
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: database
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    db_data:
